#!/usr/bin/env python3
"""Resolve Term's source version from Git metadata and generate build surfaces."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

VERSION_TAG = re.compile(r"^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")


class VersionError(RuntimeError):
    pass


@dataclass(frozen=True)
class BuildVersion:
    runtime: str
    numeric: str
    dirty: bool


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(root), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _clean_worktree(root: Path) -> bool:
    return not _git(root, "status", "--porcelain", "--untracked-files=all")


def resolve_version(root: Path, release_tag: str | None = None) -> BuildVersion:
    if release_tag is not None:
        if not VERSION_TAG.fullmatch(release_tag):
            raise VersionError(f"invalid release tag: {release_tag!r}; expected vX.Y.Z")
        try:
            head = _git(root, "rev-parse", "HEAD")
            tag_commit = _git(root, "rev-parse", "--verify", f"refs/tags/{release_tag}^{{commit}}")
            clean = _clean_worktree(root)
        except (OSError, subprocess.CalledProcessError) as error:
            raise VersionError(f"release version metadata unavailable: {error}") from error
        if head != tag_commit:
            raise VersionError("release tag does not point at HEAD")
        if not clean:
            raise VersionError("release working tree is dirty")
        version = release_tag[1:]
        return BuildVersion(version, version, False)

    try:
        sha = _git(root, "rev-parse", "--short=7", "HEAD")
    except (OSError, subprocess.CalledProcessError):
        return BuildVersion("0.0.0-dev+unknown", "0.0.0", False)

    try:
        clean = _clean_worktree(root)
    except (OSError, subprocess.CalledProcessError):
        clean = False

    try:
        exact_tags = _git(root, "tag", "--points-at", "HEAD").splitlines()
    except (OSError, subprocess.CalledProcessError):
        exact_tags = []

    exact_versions = [match for tag in exact_tags if (match := VERSION_TAG.fullmatch(tag))]
    if exact_versions:
        match = sorted(exact_versions, key=lambda item: tuple(map(int, item.groups())))[-1]
        base = ".".join(match.groups())
        if clean:
            return BuildVersion(base, base, False)
        return BuildVersion(f"{base}-dev.0+g{sha}.dirty", base, True)

    tags: list[tuple[int, str, re.Match[str]]] = []
    try:
        merged_tags = _git(root, "tag", "--merged", "HEAD").splitlines()
        for tag in merged_tags:
            match = VERSION_TAG.fullmatch(tag)
            if match is None:
                continue
            distance = int(_git(root, "rev-list", "--count", f"{tag}..HEAD"))
            tags.append((distance, tag, match))
    except (OSError, subprocess.CalledProcessError):
        tags = []

    if tags:
        distance, _, match = min(tags, key=lambda item: (item[0], item[1]))
        base = ".".join(match.groups())
        runtime = f"{base}-dev.{distance}+g{sha}"
    else:
        base = "0.0.0"
        runtime = f"{base}-dev+g{sha}"
    if not clean:
        runtime += ".dirty"
    return BuildVersion(runtime, base, not clean)


def write_outputs(version: BuildVersion, source: Path, plist: Path | None) -> None:
    source.parent.mkdir(parents=True, exist_ok=True)
    source.write_text(
        "// Generated by scripts/resolve_version.py; do not edit.\n"
        "package build_info\n\n"
        f'VERSION :: "{version.runtime}"\n'
        f'NUMERIC_VERSION :: "{version.numeric}"\n'
        f'TERM_PROGRAM_VERSION_ENV :: "TERM_PROGRAM_VERSION={version.runtime}"\n',
        encoding="utf-8",
    )
    if plist is not None:
        import plistlib

        template = Path("assets/Info.plist")
        data = plistlib.loads(template.read_bytes())
        data["CFBundleShortVersionString"] = version.numeric
        data["CFBundleVersion"] = version.numeric
        plist.parent.mkdir(parents=True, exist_ok=True)
        plist.write_bytes(plistlib.dumps(data, fmt=plistlib.FMT_XML, sort_keys=False))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--source", type=Path, default=Path("src/build_info/version.odin"))
    parser.add_argument("--plist", type=Path)
    args = parser.parse_args()

    release_tag = os.environ.get("TERM_RELEASE_TAG")
    try:
        version = resolve_version(args.root.resolve(), release_tag)
    except VersionError as error:
        print(f"version resolver: {error}", file=sys.stderr)
        return 1
    write_outputs(version, args.source, args.plist)
    print(f"Term version: {version.runtime} (bundle: {version.numeric})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
